### ISSUE TITLE
User Auth Check 

### ISSUE THREAD

**Issue by JoeBumbaca** [JoeBumbaca/UNCAPPD#2]
Hi Andy, I have pushed the app up to Heroku. The only user in the database is the Demo user.  You can access the Demo login from either of the two forms.  The pictures do not work, so I will start with Active Storage/AWS to make them accessible.

**Comment by JoeBumbaca** [comment]
Image issue fixed!

**Comment by minucos** [comment]
Hi Joe

Looks good! Just a couple quick notes on styling:

- [ ] remove left and right padding from your main-left and main-right divs
- [ ] add justify-content: center to your .main div
- [ ] add background-position: top; to your .main-right
- [ ] add display: flex; , flex-direction: column; , and align-items: center; to your .main-right;
- [ ] remove all left and right margin or padding from your .yellow-div and .splash-text

This should space your logo and images more evenly on the page


Other than that, great job!

**Comment by JoeBumbaca** [comment]
Hi Andy, I've made the adjustments.  Thank you, it does look better!

**Comment by minucos** [comment]
Nice! Issue closed, good job
